namespace Decompiler.Enums
{
	internal enum RestrictedArea
	{
		RESTRICTED_AREA_GOLF_CLUB = 1,
		RESTRICTED_AREA_LS_AIRPORT,
		RESTRICTED_AREA_FORT_ZANCUDO,
		RESTRICTED_AREA_PRISON,
		RESTRICTED_AREA_HUMAN_LABS,
		RESTRICTED_AREA_MERRYWEATHER_DOCK,
		RESTRICTED_AREA_FILM_STUDIO,
		RESTRICTED_AREA_POLICE_STATION
	};
}